### ISSUE TITLE
Project is not working directly!

### ISSUE THREAD

**Issue by vishaldhanani** [codingharbour/kafka-protobuf#2]
Hi, I have used this project to set up a demo for protobuf with java. I am not configuring locally in my IntelliJ.  Can you please advise?? 

Thank you!

**Comment by chromy96** [comment]
Hi,

If you want to run the code from terminal, you can use maven exec plugin to run the appropriate class.

First, make sure to compile the code:

`mvn clean compile`

Then you can execute the class, for example ProtobufProducer by running:

`mvn exec:java -Dexec.mainClass="com.codingharbour.kafka.protobuf.producer.ProtobufProducer"`

Rinse and repeat for other classes. 

Do note that consumer classes keep running in a while loop forever, so you'll need to stop the consumer with Ctrl+C.

**Comment by vishaldhanani** [comment]
Hi, 

Thank you for providing the steps. It's compiled and run my code now but when I am producing my message that cannot be receiving at my consumer side. I have run both the consumer and producer to send messages from producer to consumer. 
But I didn't find any reason why it is not consuming by the consumer?

Can you help me with it?

Thank you very much :)

**Comment by chromy96** [comment]
Hi,
this looks like the producer and consumer cannot find the Kafka broker. The source code assumes they're running on `localhost`, on port `9092`. I'm assuming you're running it as described in the section `Running a local Kafka cluster`in [this blog post](https://github.com/codingharbour/kafka-docker-compose/tree/master/single-node-avro-kafka). If not, check that section for instructions on how to do that.

If you see that broker is running and the port is exposed, try to connect to it with telnet, to confirm it's accessible. Try  `telnet localhost 9092`. If you get a message `Connected to localhost`then broker is available for connection.
